#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

NODEUP_URL_AMD64=https://artifacts.k8s.io/binaries/kops/1.35.1/linux/amd64/nodeup,https://github.com/kubernetes/kops/releases/download/v1.35.1/nodeup-linux-amd64
NODEUP_HASH_AMD64=b6f5dded0fabdda70d1939911a802dd52ef38e221b24b478f9fd78920223a891
NODEUP_URL_ARM64=https://artifacts.k8s.io/binaries/kops/1.35.1/linux/arm64/nodeup,https://github.com/kubernetes/kops/releases/download/v1.35.1/nodeup-linux-arm64
NODEUP_HASH_ARM64=96097ccc589a9c5dfeddb1bbe75d54194cccf2b50674025297f9177bcb52b1d3





sysctl -w net.core.rmem_max=16777216 || true
sysctl -w net.core.wmem_max=16777216 || true
sysctl -w net.ipv4.tcp_rmem='4096 87380 16777216' || true
sysctl -w net.ipv4.tcp_wmem='4096 87380 16777216' || true


function ensure-install-dir() {
  INSTALL_DIR="/opt/kops"
  # On ContainerOS, we install under /var/lib/toolbox; /opt is ro and noexec
  if [[ -d /var/lib/toolbox ]]; then
    INSTALL_DIR="/var/lib/toolbox/kops"
  fi
  mkdir -p ${INSTALL_DIR}/bin
  mkdir -p ${INSTALL_DIR}/conf
  cd ${INSTALL_DIR}
}

# Retry a download until we get it. args: name, sha, urls
download-or-bust() {
  echo "== Downloading $1 with hash $2 from $3 =="
  local -r file="$1"
  local -r hash="$2"
  local -a urls
  IFS=, read -r -a urls <<< "$3"

  if [[ -f "${file}" ]]; then
    if ! validate-hash "${file}" "${hash}"; then
      rm -f "${file}"
    else
      return 0
    fi
  fi

  while true; do
    for url in "${urls[@]}"; do
      commands=(
        "curl -f --compressed -Lo ${file} --connect-timeout 20 --retry 6 --retry-delay 10"
        "wget --compression=auto -O ${file} --connect-timeout=20 --tries=6 --wait=10"
        "curl -f -Lo ${file} --connect-timeout 20 --retry 6 --retry-delay 10"
        "wget -O ${file} --connect-timeout=20 --tries=6 --wait=10"
      )
      for cmd in "${commands[@]}"; do
        echo "== Downloading ${url} using ${cmd} =="
        if ! (${cmd} "${url}"); then
          echo "== Failed to download ${url} using ${cmd} =="
          continue
        fi
        if ! validate-hash "${file}" "${hash}"; then
          echo "== Failed to validate hash for ${url} =="
          rm -f "${file}"
        else
          echo "== Downloaded ${url} with hash ${hash} =="
          return 0
        fi
      done
    done

    echo "== All downloads failed; sleeping before retrying =="
    sleep 60
  done
}

validate-hash() {
  local -r file="$1"
  local -r expected="$2"
  local actual

  actual=$(sha256sum "${file}" | awk '{ print $1 }') || true
  if [[ "${actual}" != "${expected}" ]]; then
    echo "== File ${file} is corrupted; hash ${actual} doesn't match expected ${expected} =="
    return 1
  fi
}

function download-release() {
  case "$(uname -m)" in
  x86_64*|i?86_64*|amd64*)
    NODEUP_URL="${NODEUP_URL_AMD64}"
    NODEUP_HASH="${NODEUP_HASH_AMD64}"
    ;;
  aarch64*|arm64*)
    NODEUP_URL="${NODEUP_URL_ARM64}"
    NODEUP_HASH="${NODEUP_HASH_ARM64}"
    ;;
  *)
    echo "Unsupported host arch: $(uname -m)" >&2
    exit 1
    ;;
  esac

  cd ${INSTALL_DIR}/bin
  download-or-bust nodeup "${NODEUP_HASH}" "${NODEUP_URL}"

  chmod +x nodeup

  echo "== Running nodeup =="
  # We can't run in the foreground because of https://github.com/docker/docker/issues/23793
  ( cd ${INSTALL_DIR}/bin; ./nodeup --install-systemd-unit --conf=${INSTALL_DIR}/conf/kube_env.yaml --v=8  )
}

####################################################################################

/bin/systemd-machine-id-setup || echo "== Failed to initialize the machine ID; ensure machine-id configured =="

echo "== nodeup node config starting =="
ensure-install-dir

cat > conf/kube_env.yaml << '__EOF_KUBE_ENV'
CloudProvider: gce
ClusterName: k8s1.tomas-virgl.e2b-test.dev
ConfigServer:
  CACertificates: |
    -----BEGIN CERTIFICATE-----
    MIIC/TCCAeWgAwIBAgIRALODctwtXhWbZEKuQYKzLAowDQYJKoZIhvcNAQELBQAw
    GDEWMBQGA1UEAxMNa3ViZXJuZXRlcy1jYTAeFw0yNjA2MDIwMDUyNTJaFw0zNjA1
    MzAwMDUyNTJaMBgxFjAUBgNVBAMTDWt1YmVybmV0ZXMtY2EwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQCineuw1m/n8m3VtgB6tgNksNqETzNGwKNNSjTa
    Lhbndl/kkQppaZyDdlUtEqo+a/m3tegceB3Dc6SNpl94zjDyspWmVVE7QfBjQSVw
    7tlA9fc3ptzA2TMkaw/eOVL9UZdVrUWRM2vmDF3i3jmPA9LzXdV/nbV5AX+CJd5L
    Cfjaf+/oeU7lsF0/L5u5EunalGk7HpWHOsx9FmVNsHpgODRLwHzcQ6Nx8WMpd26D
    nEI4ftM8ivxKbZerdgXP6pj+A8HzyPWeUZJskQk3PsrxfcSFt/c7ja2ov8pOMHrx
    ybvhFMua8WysZH6mj9z7+ynZk6lLo8DZ/66i+T/EYcqPdcVBAgMBAAGjQjBAMA4G
    A1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSOOR6BFiYr
    ZQr0/oIORH1cykiedDANBgkqhkiG9w0BAQsFAAOCAQEAVPkiUhh5qCeMOiDeTRUU
    sayl6lMXPV6ZOv+fqXscKfxfqOMG2N7lZo3oIn0UQAtFsgHleKasMDsoIOAKOnJe
    QAmOIHAHSkdEL2b3OQoPF1OvP+Mpit2U1WaFvQfkb43AZmzfb73D9CQGEexTT/px
    KBMjleg4QviGHlcs2B0OCQMWoRX10cEdEArExyjz/JhOY8EXpxNChZbW//XQrWZd
    ZujeTRJi1IJmq/CZemzFkHdoe0GzyIjcmLfASjFHjqU07U3zVyp65BvSiqzw2uQt
    IsEENsL6WHZDqutbYeUcQrTeUoEXfgT3+zYUG+SMtfqyFbvq0mFgCSDxIl2/hJHG
    bw==
    -----END CERTIFICATE-----
  servers:
  - https://kops-controller.internal.k8s1.tomas-virgl.e2b-test.dev:3988/
InstanceGroupName: nodes-us-west1-c
InstanceGroupRole: Node
NodeupConfigHash: TrtjPB4NEV3LBXJH/ekbLup7fkg4jbMSegL3047vAiE=

__EOF_KUBE_ENV

download-release
echo "== nodeup node config done =="
